### ISSUE TITLE
Is the latest plugin applied from the caddy download?

### ISSUE THREAD

**Issue by kenfdev** [BTBurke/caddy-jwt#16]
Hi,
First of all, thanks for this excellent jwt plugin for caddy.  I really appreciate it.
I was wondering if the latest version is applied to the official caddy site's download.
I've downloaded caddy today with `jwt` included and I can confirm receiving a `401` without a valid jwt but the `redirect` option doesn't seem to be working.
The `jwt` directive is as below but I still only get `401 Unauthorized` page.

```
jwt {
  path /secret_path
  redirect /login
}
```

Apologies if my configuration is mistaken.
Any support would help me a lot.

Thanks in advance.

**Comment by BTBurke** [comment]
The redirect feature probably isn't included in the latest release from the website.  I just merged that a few weeks ago.  The build server caches the plugins until the next Caddy release comes out.   They are working on a new build server that lets plugin authors trigger a new build, but until that comes out you will have to build Caddy from source to get the latest plugin features.

There are directions for building Caddy at https://github.com/mholt/caddy.  If you build from source and still have problems, let me know.

**Comment by kenfdev** [comment]
@BTBurke Thanks for the reply.  So i guess it isn't included at the moment.  I've tried building caddy from source but it didn't succeed in the first try (some error from caddytls).  Well, I guess I'll wait for the next version of caddy. Thanks anyway!  I'll close the issue.
