### ISSUE TITLE
Recent caddy-jwt in caddy release

### ISSUE THREAD

**Issue by lucafavatella** [BTBurke/caddy-jwt#18]
I understand the version of caddy-jwt in caddy does not include RSA - see https://caddyserver.com/docs/jwt

I read https://github.com/BTBurke/caddy-jwt/pull/15#issuecomment-276120024

How can contributions speed up inclusion of recent caddy-jwt with RSA support in upstream caddy release?

**Comment by BTBurke** [comment]
We are testing a new build server that will allow the plugins to be updated independently of the release timeline for main Caddy.  I'm not sure when it will go live. Until then you have to build caddy from source to get the latest features of caddy-jwt included. 
On Wednesday, April 5, 2017 at 6:44 AM Luca Favatella <notifications@github.com> wrote:

I understand the version of caddy-jwt in caddy does not include RSA - see https://caddyserver.com/docs/jwt

I read #15 (comment)

How can contributions speed up inclusion of recent caddy-jwt with RSA support in upstream caddy release?

**Comment by lucafavatella** [comment]
Thanks. I need to find out how to build caddy with caddy-jwt then.

**Comment by mholt** [comment]
April 20 :tada:
