### ISSUE TITLE
Multiple auth provider trust.

### ISSUE THREAD

**Issue by Shadowfaxenator** [BTBurke/caddy-jwt#27]
Is there any way to add several public keys to verify JWT?
I want to trust multiple hosts which provide JWT tokens.

**Comment by BTBurke** [comment]
Do you mean for a single site?  Currently there's no way to specify multiple public keys.  What's the use case for this?  Is it for JWTs that may be issued by different third-party services?

**Comment by Shadowfaxenator** [comment]
Yes exactly. To trust several providers

**Comment by BTBurke** [comment]
Ok I think this is pretty straightforward.  The best way would probably be to allow multiple `publickey` declarations like:

```
publickey /path/to/first.key
publickey /path/to/second.key
```

**Comment by BTBurke** [comment]
This is implemented now in v2.6.0.  Use the multiple declaration syntax in my comment above to use it.
