### ISSUE TITLE
Support for other Authorization header formats

### ISSUE THREAD

**Issue by icb-** [BTBurke/caddy-jwt#46]
I would like to be able to use this for Apple PassKit passes, which means checking the `Authorization` header for a `ApplePass <token>` instead of `Bearer <token>`. Can we relax the [check for `Bearer`](https://github.com/BTBurke/caddy-jwt/blob/81c4f1e36d4c7edbb481f7d9b95393e296657787/jwt.go#L27) to allow any string, or a configurable one?

**Comment by BTBurke** [comment]
Sure, but I don't have time to implement this.  If you know go, I'll accept a pull request.  Basically how it should work is that it should build on the directive `token_source header` directive and be something like `token_source header applepass`.
