### ISSUE TITLE
Question about releases

### ISSUE THREAD

**Issue by xombiemp** [BTBurke/caddy-jwt#54]
This is not an issue, just a question so I can understand Go better.

In the Releases the most recent release is 3.7.2.

If I do
`go get github.com/BTBurke/caddy-jwt`
Go gets v3.7.1.

> caddy-jwt@v3.7.1+incompatible

Why is that?

**Comment by BTBurke** [comment]
Actually I think I screwed up and 3.7.1 and 3.7.2 point to the same commit.
