### ISSUE TITLE
Advice on secret file format for HMAC

### ISSUE THREAD

**Issue by PictureMil** [BTBurke/caddy-jwt#60]
Hi Bryan. Not an issue in your code, so much as a daft question from a Caddy/JWT/Linux newbie! Apologies in advance but I have struggled to find any detailed docs on how to declare `JWT_SECRET` in my secret file.

If my secret was "opensesame", is the contents of my file simply...
```
JWT_SECRET='opensesame'
```
I suspect not because I can't get my setup to work.

**Comment by BTBurke** [comment]
Just put your secret in the file, no need to do key=value.  It can be a plain text file with opensesame in it.

**Comment by PictureMil** [comment]
Hello! Thanks for that. Validation works now. You can close this issue now, but I still have bigger problems that I am discussing here:
https://caddy.community/t/securing-my-proxied-server-advice-please/6922
Best, m
