### ISSUE TITLE
allow access for groups

### ISSUE THREAD

**Issue by greenpau** [BTBurke/caddy-jwt#61]
JWT token has the following claims:

```jwt
{
  "name": "Greenberg, Paul",
  "groups": [
    "AzureAD_Administrator",
    "AzureAD_Editor"
  ]
}
```

What is the way to allow access to a page for anyone in `AzureAD_Administrator` group?

**Comment by BTBurke** [comment]
Try 

`allow groups.0 AzureAD_Administrator`

**Comment by greenpau** [comment]
> Try `allow groups.0 AzureAD_Administrator`

@BTBurke,  thank you, but it did not work 👍 I will continue troubleshooting.

What if `AzureAD_Administrator` is 2nd element? What is your vision to accomplish the matching according to group membership?

**Comment by greenpau** [comment]
> allow groups.0 AzureAD_Administrator

@BTBurke , the above does not work because the evaluations below, i.e. `vClaims` only contains `groups`.

```
        // If token contains rules with allow or deny, evaluate
        if len(p.AccessRules) > 0 {
            var isAuthorized []bool
            for _, rule := range p.AccessRules {
                v := vClaims[rule.Claim]
```

There is actually a login to check whether something is a slice (array) and match on it. In theory, the `allow groups AzureAD_Administrator` should be working.

To be continued...

**Comment by greenpau** [comment]
The `allow groups AzureAD_Administrator` works. It was not working because of browser cache.

**Comment by BTBurke** [comment]
Great. I thought it should have worked. Cheers.
