### ISSUE TITLE
JWT custom-claims as var

### ISSUE THREAD

**Issue by aios** [BTBurke/caddy-jwt#7]
So i want get a custom claims as var and proxy that requests.
It's possible with your plugin?

**Comment by BTBurke** [comment]
Yes the claims are passed in the headers.  You can check out the section of the docs where it talks about [acting on claims in the token](https://github.com/BTBurke/caddy-jwt#acting-on-claims-in-the-token)

**Comment by aios** [comment]
So if i have many jwt parts? what kind of behavior i will wait?
